fix expandable search bar issue w/ the dropdown options (quick search)
internetarchive/iaux pull request #553
Opened 2021-04-18 01:49 UTC by hotzjacobb

**Description**

This PR addresses issue #528. The issue was actually broader than described. The expandable search bar was actually unable to use the dropdown options after any user input keystrokes. This PR fixes that and it now works as intended.

**Technical**

The existing code didn't work because it tried to modify a LitElement component from outside the component. LitElement, like similar frameworks, updates the DOM based on changes to state inside components. Also, the previous implementation placed a non-documented obligation on the consumer to know that they must write this supporting code.

This implementation fixes this by changing state from within the component.

I also would like to note that I discovered another pre-existing problem while fixing this, but that goes beyond the scope of this PR. Both `this.searchTerm` and `this.searchInput.value` hold overlapping state information for text in the search bar. I tried to see if there was a simple fix by looking at LitElement's documentation, but it seemed like it would take more digging or someone with more experience with that framework. A simple solution might be converting this to React. I can file an issue if need be.

**Testing**

See if the expandable search bar correctly takes new input after from the drop-down menu/the expandable search bar works in general.

**Evidence**

https://user-images.githubusercontent.com/34525444/115131511-85ed1d80-9fad-11eb-8a2e-593d73874ad0.mov

2021-05-26 03:38 UTC, hotzjacobb commented on packages/expandable-search-bar/src/expandable-search-bar.ts
> +  //       searchInput.value should not also affect state
Thanks; used in 247c417

2021-05-26 19:34 UTC, jbuckner requested changes

2021-05-26 19:34 UTC, jbuckner commented on packages/expandable-search-bar/src/expandable-search-bar.ts
> +      }
The `updated()` method gets called when any of the properties get updated so we'd want to limit this to just when `searchTerm` is updated. You can add the [`(props: PropertyValues)`](https://lit.dev/docs/components/lifecycle/#updated) argument to the method which contains all of the properties that were updated, ie `if (props.has('searchTerm')) { ... }`.

Also, could you reindent to 2 spaces?

2021-05-26 19:34 UTC, jbuckner commented on packages/expandable-search-bar/src/expandable-search-bar.ts
> +   * Workaround for lit-element 2.2.1 not reflecting this.searchTerm
This isn't really a workaround so much as how form inputs work. The `searchTerm` property isn't bound to the input's value as a reactive property so you have to do set it when the value gets updated.

2021-05-28 23:10 UTC, jbuckner requested changes
I tested the branch and the functionality looks good except for focusing the search box after clearing. Update that and add the return type to `updated()` and this PR should be good to go.

2021-05-28 23:10 UTC, jbuckner commented on packages/expandable-search-bar/src/expandable-search-bar.ts
> -      this.searchInput.focus();
We want to still keep the `searchInput` in focus after clearing the search.

2021-05-28 23:10 UTC, jbuckner commented on packages/expandable-search-bar/src/expandable-search-bar.ts
> +  updated(props: PropertyValues) {
Could you add a `: void` return type to this?

2021-06-03 15:51 UTC, jbuckner approved these changes
Looks good! Thank you for the fix!

2021-06-03 15:51 UTC, merged